// Copyright Epic Games, Inc. All Rights Reserved.


// Auto-generated by spvreflect please don't modify by hand

#pragma once

struct CalculateDataTermReflection
{
	static constexpr uint32_t dsetCount { 1 };


	struct DescSet0_Init
	{
		VkDescriptorSetLayoutBinding bindings[15];
		uint32_t					 nBindings { 15 };

		DescSet0_Init()
		{
			// Binding for:Ix
			bindings[0] =
				VkDescriptorSetLayoutBinding
				{
					/*.binding*/ 0,
					/*.descriptorType*/ VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
					/*.descriptorCount*/ 1,
					/*.stageFlags*/ VK_SHADER_STAGE_COMPUTE_BIT,
					/*.pImmutableSamplers*/ nullptr
				};
			// Binding for:Iy
			bindings[1] =
				VkDescriptorSetLayoutBinding
				{
					/*.binding*/ 1,
					/*.descriptorType*/ VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
					/*.descriptorCount*/ 1,
					/*.stageFlags*/ VK_SHADER_STAGE_COMPUTE_BIT,
					/*.pImmutableSamplers*/ nullptr
				};
			// Binding for:Iz
			bindings[2] =
				VkDescriptorSetLayoutBinding
				{
					/*.binding*/ 2,
					/*.descriptorType*/ VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
					/*.descriptorCount*/ 1,
					/*.stageFlags*/ VK_SHADER_STAGE_COMPUTE_BIT,
					/*.pImmutableSamplers*/ nullptr
				};
			// Binding for:Ixx
			bindings[3] =
				VkDescriptorSetLayoutBinding
				{
					/*.binding*/ 3,
					/*.descriptorType*/ VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
					/*.descriptorCount*/ 1,
					/*.stageFlags*/ VK_SHADER_STAGE_COMPUTE_BIT,
					/*.pImmutableSamplers*/ nullptr
				};
			// Binding for:Ixy
			bindings[4] =
				VkDescriptorSetLayoutBinding
				{
					/*.binding*/ 4,
					/*.descriptorType*/ VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
					/*.descriptorCount*/ 1,
					/*.stageFlags*/ VK_SHADER_STAGE_COMPUTE_BIT,
					/*.pImmutableSamplers*/ nullptr
				};
			// Binding for:Iyy
			bindings[5] =
				VkDescriptorSetLayoutBinding
				{
					/*.binding*/ 5,
					/*.descriptorType*/ VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
					/*.descriptorCount*/ 1,
					/*.stageFlags*/ VK_SHADER_STAGE_COMPUTE_BIT,
					/*.pImmutableSamplers*/ nullptr
				};
			// Binding for:Ixz
			bindings[6] =
				VkDescriptorSetLayoutBinding
				{
					/*.binding*/ 6,
					/*.descriptorType*/ VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
					/*.descriptorCount*/ 1,
					/*.stageFlags*/ VK_SHADER_STAGE_COMPUTE_BIT,
					/*.pImmutableSamplers*/ nullptr
				};
			// Binding for:Iyz
			bindings[7] =
				VkDescriptorSetLayoutBinding
				{
					/*.binding*/ 7,
					/*.descriptorType*/ VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
					/*.descriptorCount*/ 1,
					/*.stageFlags*/ VK_SHADER_STAGE_COMPUTE_BIT,
					/*.pImmutableSamplers*/ nullptr
				};
			// Binding for:dW_u
			bindings[8] =
				VkDescriptorSetLayoutBinding
				{
					/*.binding*/ 8,
					/*.descriptorType*/ VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
					/*.descriptorCount*/ 1,
					/*.stageFlags*/ VK_SHADER_STAGE_COMPUTE_BIT,
					/*.pImmutableSamplers*/ nullptr
				};
			// Binding for:dW_v
			bindings[9] =
				VkDescriptorSetLayoutBinding
				{
					/*.binding*/ 9,
					/*.descriptorType*/ VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
					/*.descriptorCount*/ 1,
					/*.stageFlags*/ VK_SHADER_STAGE_COMPUTE_BIT,
					/*.pImmutableSamplers*/ nullptr
				};
			// Binding for:A11
			bindings[10] =
				VkDescriptorSetLayoutBinding
				{
					/*.binding*/ 10,
					/*.descriptorType*/ VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
					/*.descriptorCount*/ 1,
					/*.stageFlags*/ VK_SHADER_STAGE_COMPUTE_BIT,
					/*.pImmutableSamplers*/ nullptr
				};
			// Binding for:A12
			bindings[11] =
				VkDescriptorSetLayoutBinding
				{
					/*.binding*/ 11,
					/*.descriptorType*/ VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
					/*.descriptorCount*/ 1,
					/*.stageFlags*/ VK_SHADER_STAGE_COMPUTE_BIT,
					/*.pImmutableSamplers*/ nullptr
				};
			// Binding for:A22
			bindings[12] =
				VkDescriptorSetLayoutBinding
				{
					/*.binding*/ 12,
					/*.descriptorType*/ VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
					/*.descriptorCount*/ 1,
					/*.stageFlags*/ VK_SHADER_STAGE_COMPUTE_BIT,
					/*.pImmutableSamplers*/ nullptr
				};
			// Binding for:b1
			bindings[13] =
				VkDescriptorSetLayoutBinding
				{
					/*.binding*/ 13,
					/*.descriptorType*/ VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
					/*.descriptorCount*/ 1,
					/*.stageFlags*/ VK_SHADER_STAGE_COMPUTE_BIT,
					/*.pImmutableSamplers*/ nullptr
				};
			// Binding for:b2
			bindings[14] =
				VkDescriptorSetLayoutBinding
				{
					/*.binding*/ 14,
					/*.descriptorType*/ VK_DESCRIPTOR_TYPE_STORAGE_BUFFER,
					/*.descriptorCount*/ 1,
					/*.stageFlags*/ VK_SHADER_STAGE_COMPUTE_BIT,
					/*.pImmutableSamplers*/ nullptr
				};
		}
	};

	struct DescSet0_Update
	{
		VkWriteDescriptorSet		writes[15];
		uint32_t					nWrites { 15 };

		VkDescriptorBufferInfo		IxDesc{ VK_NULL_HANDLE, 0, VK_WHOLE_SIZE };
		VkDescriptorBufferInfo		IyDesc{ VK_NULL_HANDLE, 0, VK_WHOLE_SIZE };
		VkDescriptorBufferInfo		IzDesc{ VK_NULL_HANDLE, 0, VK_WHOLE_SIZE };
		VkDescriptorBufferInfo		IxxDesc{ VK_NULL_HANDLE, 0, VK_WHOLE_SIZE };
		VkDescriptorBufferInfo		IxyDesc{ VK_NULL_HANDLE, 0, VK_WHOLE_SIZE };
		VkDescriptorBufferInfo		IyyDesc{ VK_NULL_HANDLE, 0, VK_WHOLE_SIZE };
		VkDescriptorBufferInfo		IxzDesc{ VK_NULL_HANDLE, 0, VK_WHOLE_SIZE };
		VkDescriptorBufferInfo		IyzDesc{ VK_NULL_HANDLE, 0, VK_WHOLE_SIZE };
		VkDescriptorBufferInfo		dW_uDesc{ VK_NULL_HANDLE, 0, VK_WHOLE_SIZE };
		VkDescriptorBufferInfo		dW_vDesc{ VK_NULL_HANDLE, 0, VK_WHOLE_SIZE };
		VkDescriptorBufferInfo		A11Desc{ VK_NULL_HANDLE, 0, VK_WHOLE_SIZE };
		VkDescriptorBufferInfo		A12Desc{ VK_NULL_HANDLE, 0, VK_WHOLE_SIZE };
		VkDescriptorBufferInfo		A22Desc{ VK_NULL_HANDLE, 0, VK_WHOLE_SIZE };
		VkDescriptorBufferInfo		b1Desc{ VK_NULL_HANDLE, 0, VK_WHOLE_SIZE };
		VkDescriptorBufferInfo		b2Desc{ VK_NULL_HANDLE, 0, VK_WHOLE_SIZE };

		DescSet0_Update(VkBuffer Ix, VkBuffer Iy, VkBuffer Iz, VkBuffer Ixx, VkBuffer Ixy, VkBuffer Iyy, VkBuffer Ixz, VkBuffer Iyz, VkBuffer dW_u, VkBuffer dW_v, VkBuffer A11, VkBuffer A12, VkBuffer A22, VkBuffer b1, VkBuffer b2)
		{
			IxDesc.buffer = Ix;

			writes[0] = {};
			writes[0].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
			writes[0].pNext = nullptr;
            writes[0].dstSet = 0;
            writes[0].dstBinding = 0;
            writes[0].descriptorCount = 1;
            writes[0].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
            writes[0].pBufferInfo = &IxDesc;

			IyDesc.buffer = Iy;

			writes[1] = {};
			writes[1].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
			writes[1].pNext = nullptr;
            writes[1].dstSet = 0;
            writes[1].dstBinding = 1;
            writes[1].descriptorCount = 1;
            writes[1].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
            writes[1].pBufferInfo = &IyDesc;

			IzDesc.buffer = Iz;

			writes[2] = {};
			writes[2].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
			writes[2].pNext = nullptr;
            writes[2].dstSet = 0;
            writes[2].dstBinding = 2;
            writes[2].descriptorCount = 1;
            writes[2].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
            writes[2].pBufferInfo = &IzDesc;

			IxxDesc.buffer = Ixx;

			writes[3] = {};
			writes[3].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
			writes[3].pNext = nullptr;
            writes[3].dstSet = 0;
            writes[3].dstBinding = 3;
            writes[3].descriptorCount = 1;
            writes[3].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
            writes[3].pBufferInfo = &IxxDesc;

			IxyDesc.buffer = Ixy;

			writes[4] = {};
			writes[4].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
			writes[4].pNext = nullptr;
            writes[4].dstSet = 0;
            writes[4].dstBinding = 4;
            writes[4].descriptorCount = 1;
            writes[4].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
            writes[4].pBufferInfo = &IxyDesc;

			IyyDesc.buffer = Iyy;

			writes[5] = {};
			writes[5].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
			writes[5].pNext = nullptr;
            writes[5].dstSet = 0;
            writes[5].dstBinding = 5;
            writes[5].descriptorCount = 1;
            writes[5].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
            writes[5].pBufferInfo = &IyyDesc;

			IxzDesc.buffer = Ixz;

			writes[6] = {};
			writes[6].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
			writes[6].pNext = nullptr;
            writes[6].dstSet = 0;
            writes[6].dstBinding = 6;
            writes[6].descriptorCount = 1;
            writes[6].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
            writes[6].pBufferInfo = &IxzDesc;

			IyzDesc.buffer = Iyz;

			writes[7] = {};
			writes[7].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
			writes[7].pNext = nullptr;
            writes[7].dstSet = 0;
            writes[7].dstBinding = 7;
            writes[7].descriptorCount = 1;
            writes[7].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
            writes[7].pBufferInfo = &IyzDesc;

			dW_uDesc.buffer = dW_u;

			writes[8] = {};
			writes[8].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
			writes[8].pNext = nullptr;
            writes[8].dstSet = 0;
            writes[8].dstBinding = 8;
            writes[8].descriptorCount = 1;
            writes[8].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
            writes[8].pBufferInfo = &dW_uDesc;

			dW_vDesc.buffer = dW_v;

			writes[9] = {};
			writes[9].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
			writes[9].pNext = nullptr;
            writes[9].dstSet = 0;
            writes[9].dstBinding = 9;
            writes[9].descriptorCount = 1;
            writes[9].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
            writes[9].pBufferInfo = &dW_vDesc;

			A11Desc.buffer = A11;

			writes[10] = {};
			writes[10].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
			writes[10].pNext = nullptr;
            writes[10].dstSet = 0;
            writes[10].dstBinding = 10;
            writes[10].descriptorCount = 1;
            writes[10].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
            writes[10].pBufferInfo = &A11Desc;

			A12Desc.buffer = A12;

			writes[11] = {};
			writes[11].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
			writes[11].pNext = nullptr;
            writes[11].dstSet = 0;
            writes[11].dstBinding = 11;
            writes[11].descriptorCount = 1;
            writes[11].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
            writes[11].pBufferInfo = &A12Desc;

			A22Desc.buffer = A22;

			writes[12] = {};
			writes[12].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
			writes[12].pNext = nullptr;
            writes[12].dstSet = 0;
            writes[12].dstBinding = 12;
            writes[12].descriptorCount = 1;
            writes[12].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
            writes[12].pBufferInfo = &A22Desc;

			b1Desc.buffer = b1;

			writes[13] = {};
			writes[13].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
			writes[13].pNext = nullptr;
            writes[13].dstSet = 0;
            writes[13].dstBinding = 13;
            writes[13].descriptorCount = 1;
            writes[13].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
            writes[13].pBufferInfo = &b1Desc;

			b2Desc.buffer = b2;

			writes[14] = {};
			writes[14].sType = VK_STRUCTURE_TYPE_WRITE_DESCRIPTOR_SET;
			writes[14].pNext = nullptr;
            writes[14].dstSet = 0;
            writes[14].dstBinding = 14;
            writes[14].descriptorCount = 1;
            writes[14].descriptorType = VK_DESCRIPTOR_TYPE_STORAGE_BUFFER;
            writes[14].pBufferInfo = &b2Desc;
		}

	};
};

